added card for member's profile
WTMBamenda/wtm-bamenda-website-frontend pull request #15
Opened 2023-10-13 03:09 UTC by Dabi-ayu

#8 

https://github.com/WTMBamenda/wtm-bamenda-website-frontend/assets/126058360/fbebc038-731e-4f33-8ca2-99148bd8df09

2023-10-13 03:11 UTC, Dabi-ayu commented
if there's any adjustments to be made let me know lead😊

2023-10-14 05:27 UTC, Idadelveloper requested changes
@Dabi-ayu please adjust the height of the image so that it doesn't look compressed. The picture you sent makes it looks squished.

2023-10-14 06:18 UTC, Dabi-ayu commented
> @Dabi-ayu please adjust the height of the image so that it doesn't look compressed. The picture you sent makes it looks squished.

hello team lead, i followed the height and width specified on the design, and i noticed that all images are not thesame so will need different adjustedments when they'll be included, so it's not squished. so it means i'll have to change the specifications of the design right?

2023-10-16 07:23 UTC, Idadelveloper approved these changes

2023-10-16 07:25 UTC, merged